In [44]:
import pyclifford as tc
import numpy as np

In [19]:
tc.paulialg.pauli('iXXIZZ'), 1j*tc.paulialg.pauli('XXIZZ'), tc.paulialg.pauli([0, 1, 2, 3])

(+iXXIZZ, +iXXIZZ,  +IXYZ)

In [35]:
tc.paulialg.pauli('XXIZZ').N, tc.paulialg.pauli('XXIZZ').trace(), tc.paulialg.pauli('XXIZZ').weight()

(5, 0, 4)

In [21]:
tc.paulialg.paulis('ZZ', 'XX')

 +ZZ
 +XX

In [22]:
(tc.paulialg.pauli('ZZ') + tc.paulialg.pauli('ZX') + 1)/2

0.50 II +0.50 ZZ +0.50 ZX

In [33]:
((tc.paulialg.pauli('X') + tc.paulialg.pauli('Z')) @ (tc.paulialg.pauli('X') + tc.paulialg.pauli('Z'))).reduce()

2 I

In [40]:
tc.paulialg.paulis('II','XX','YY','ZZ').rotate_by(tc.paulialg.pauli('XI'))

 +II
 +XX
 +ZY
 -YZ

In [42]:
tc.stabilizer.random_clifford_map(2)

CliffordMap(
  X0-> -ZX
  Z0-> +ZZ
  X1-> +YY
  Z1-> -ZI)

In [43]:
tc.paulialg.paulis('II','XX','YY','ZZ').transform_by(tc.stabilizer.random_clifford_map(2))

 +II
 -XZ
 +XI
 +IZ

In [45]:
mask = np.array([True,False,False,True])
tc.paulialg.paulis('IIII','XXXX', 'ZZZZ').rotate_by(tc.paulialg.pauli('XY'), mask)

 +IIII
 -IXXZ
 +ZZZZ

In [46]:
tc.paulialg.pauli('XY').to_qutip()

Quantum object: dims=[[2, 2], [2, 2]], shape=(4, 4), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]]

In [47]:
tc.stabilizer.random_clifford_map(4)

CliffordMap(
  X0-> +XIII
  Z0-> -ZYYI
  X1-> +XYXI
  Z1-> -IIYI
  X2-> +IIIY
  Z2-> -XXYZ
  X3-> -XXYI
  Z3-> -XZYY)

In [48]:
tc.stabilizer.maximally_mixed_state(4)

StabilizerState()

In [52]:
tc.stabilizer.zero_state(4), tc.stabilizer.one_state(4).ps

(StabilizerState(
    +ZIII
    +IZII
    +IIZI
    +IIIZ),
 array([2, 2, 2, 2, 2, 2, 2, 2]))

In [54]:
tc.stabilizer.ghz_state(4)

StabilizerState(
   +ZZII
   +IZZI
   +IIZZ
   +XXXX)

In [65]:
tc.stabilizer.stabilizer_state('XXY','ZZI')[:]

 +IZX
 +XXY
 +ZZI
 +XXI
 +IIX
 +XII

In [66]:
tc.stabilizer.stabilizer_state('XXY','ZZI').to_qutip()

Quantum object: dims=[[2, 2, 2], [2, 2, 2]], shape=(8, 8), type='oper', dtype=CSR, isherm=True
Qobj data =
[[0.25+0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j
  0.  +0.j   0.  -0.25j]
 [0.  +0.j   0.25+0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j
  0.  +0.25j 0.  +0.j  ]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j
  0.  +0.j   0.  +0.j  ]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j
  0.  +0.j   0.  +0.j  ]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j
  0.  +0.j   0.  +0.j  ]
 [0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j
  0.  +0.j   0.  +0.j  ]
 [0.  +0.j   0.  -0.25j 0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j
  0.25+0.j   0.  +0.j  ]
 [0.  +0.25j 0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j   0.  +0.j
  0.  +0.j   0.25+0.j  ]]

In [68]:
state = tc.stabilizer.ghz_state(3)
print(state.measure(tc.paulialg.paulis('ZII','IZI','IIZ')))
print(state.measure(tc.paulialg.paulis('ZII','IZI','IIZ')))

(array([1, 1, 1]), -1.0)
(array([1, 1, 1]), 0.0)


In [75]:
state = tc.stabilizer.ghz_state(100)
state.expect(tc.paulialg.paulis('Y'*20+'X'*80,'Z'*100))

array([1, 1])

In [76]:
state2 = tc.stabilizer.random_clifford_state(100)
print("State overlap is:", state.expect(state2))

State overlap is: 1.5777218104420236e-30


In [77]:
gate = tc.circuit.CliffordGate(1,2)

In [80]:
gate.set_forward_map(tc.stabilizer.random_clifford_map(2))

In [83]:
gate.backward_map

In [84]:
gate.compile()

[1,2]

In [85]:
gate.backward_map

CliffordMap(
  X0-> +XZ
  Z0-> -XX
  X1-> +XI
  Z1-> +ZY)

In [86]:
psi = tc.stabilizer.zero_state(4)

In [87]:
psi

StabilizerState(
   +ZIII
   +IZII
   +IIZI
   +IIIZ)

In [88]:
gate.forward(psi)

StabilizerState(
   +ZIII
   +IYZI
   +IXXI
   +IIIZ)

In [89]:
psi

StabilizerState(
   +ZIII
   +IYZI
   +IXXI
   +IIIZ)

In [91]:
circlayer = tc.circuit.CliffordLayer()
circlayer.take(tc.circuit.CliffordGate(0,1))
circlayer.take(tc.circuit.CliffordGate(1,3))

In [92]:
circlayer

|[0,1][1,3]|

In [95]:
circ = tc.circuit.CliffordCircuit(N=70)
circ.take(tc.circuit.CliffordGate(0,1))
circ.take(tc.circuit.CliffordGate(60,61))

CliffordCircuit(
  |[0,1][60,61]|)

In [99]:
circ.take(tc.circuit.CliffordGate(1, 2))

CliffordCircuit(
  |[1,2]|
  |[0,1][60,61]|)

In [100]:
circ.first_layer

|[0,1][60,61]|

In [101]:
circ.last_layer

|[1,2]|

In [105]:
psi = tc.stabilizer.zero_state(61)
circ.forward(psi)

StabilizerState(
   +ZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIIIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIIIIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIIIIIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIIIIIIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIIIIIIIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIIIIIIIIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIIIIIIIIIIIZIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
   +IIII